### ISSUE TITLE
Add multiple roles

### ISSUE THREAD

**Issue by WTFKr0** [cuigh/prometheus#5]
Like in prometheus service discovery, i would like to add the ability to scrap services instead of tasks
We have to permit user to do both on the same service too, with different metric path

On kubernetes, there is no problem, as the labels are on different objects (service vs pod)
Here i think we have to double labels specifically for that use case, like : 
- prometheus.service.enable
- prometheus.service.network
- prometheus.service.port
- etc...

WDYT ?

**Comment by cuigh** [comment]
Would you give an example? Especially why we need both on the same service?

**Comment by WTFKr0** [comment]
1) Simple example : 

You want to run a prometheus mongodb exporter in a swarm service with 2 replicas
You want prometheus auto discover it
Prometheus should discover only the VIP of the service and scrap it
If prometheus scraps the replicas, it's not what you want

2) Both on same service : 

I got a service written in nodejs (expressjs) with a mongo backend
I expose prometheus metrics of expressjs on /metrics, each replicas have to be scrapped, so current implementation is good for that
I also expose application specific metrics on /app-metrics, like counters from the mongo backend. For that, currently i manually configure promtheus to scrap myapp/app-metrics. Only the service should be scrapped here

**Comment by cuigh** [comment]
1. How about  adding a 'prometheus.mode' label? The value can be 'task' or 'service', default to 'task' to keep compatibility. Actually, for an exporter service, you can also set replica to one with restart strategy set to restart-always to achieve the same goal now.
2. For scene 2, Separating service metrics to an independent exporter looks better, for it keeps the discovery more simpler and more clearer.

**Comment by WTFKr0** [comment]
Yes seems a good point
I think my case with both needs is not a good thing :+1: 
I'll try to do it with the `prometheus.mode` label to switch modes

**Comment by WTFKr0** [comment]
I update the PR
